# Generated by Django 3.2.5 on 2021-08-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_categoty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categoty',
            new_name='category',
        ),
    ]
