# Generated by Django 3.2.5 on 2021-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={'verbose_name': 'cartlist', 'verbose_name_plural': 'cartlist'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
